---
title: "Questions for Consideration"
author: "Allison Theobold"
date: "October 12, 2018"
output: html_document
---

The following are lingering questions that I have been considering as I reason through my study. I would appreciate any and all feedback you may have on these questions at the proposal. 

1. What is my interpretive framework for the workshop design study? 

- I believe that the focus of each workshop is related to:
    * applications of the computing tools to field related tasks  
    * the nature of field norms (computing within a discipline) 
    * workshop discourse around computational concepts  

<!-- - Forms of computational reasoning adults develop are shaped by  -->
<!--     * the settings of their learning  -->
<!--     * by the collective practices they participate in while learning (Hall, 2001; Hoyles, Noss, Pozzi, 2001).   -->
    
2. What should the units of analysis be for the workshops? Individuals? Groups? Entire workshop? 

- In interviewing *individuals* about their workshop experiences am I focusing on the individual? Can this also catch a "glimpse" at group and/or workshop dynamics?  
 

3. Should the workshops be audio or video recorded? 

- Would recording the workshops allow me to properly describe the changes in workshop environment 

4. Will a pre-workshop "diagnostic" interview suffice for tracking the "intervention" group's computational knowledge?  
- Hutchins advocates for "diagnostic assessments to help track development of the participating students' reasoning during the study". 

5. If I am to analyze what transpired during each workshop, in order to plan for upcoming workshops, how long should I space the workshops out by? One (potentially repeated) workshop per month?

6. In my retrospective analysis I need to have the ability to, (1) detail "how each successive form of reasoning emerged as a reorganization of prior forms of reasoning," and (2) identify "the aspects of the workshop learning environment that supported the students' development of these successive forms of reasoning" (Hutchins, 2017).  

7. The argumentative grammar for design studies, outlined by Hutchins, states that I need to have the ability to convince others that "the students would not have developed the documented forms of computational skills but for their participation in the design study." Does this warrent the comparison of the results for RQ2 between the "control" and "intervention" cohorts?  

8. Do my current demographic surveys for workshop participants allow for me to separate the necessary aspects of the workshop learning environment from those that are contingent on different samples of participants? 

- This is the second aspect of the argumentative grammar outlined by Hutchins. I should aim to have the ability to make explicit the conditions under which these workshops can be successfully implemented. 